DROP TABLE creatureMovesEquipped;
DROP TABLE creatureMovesOwned;

CREATE TABLE IF NOT EXISTS creatureMovesOwned (
	id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY UNIQUE,
	td TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),

	creatureId INTEGER UNSIGNED,

	idx VARCHAR(100) NOT NULL,
	equipped BOOLEAN NOT NULL DEFAULT FALSE,

	CONSTRAINT FOREIGN KEY fk_creatureMovesOwned_creatures(creatureId) REFERENCES creatures(id) ON UPDATE CASCADE ON DELETE CASCADE
);
